---
version: '3.6'
services:
  traefik:
    container_name: traefik
    image: traefik:${TRAEFIKVERSION}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $(pwd)/conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - $(pwd)/conf/traefikdynamic:/traefikdynamic:ro
      - $(pwd)/logs/traefik.log:/etc/traefik/applog.log
      - $(pwd)/conf/acme.json:/acme.json
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TRAEFIK_PILOT_DASHBOARD=false"

  sqlghost:
    container_name: sqlghost
    image: mariadb:${MARIADBVERSION}
    restart: unless-stopped
    volumes:
      - $(pwd)/conf/custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf
      - datasqlghostlog:/var/log/mysql
      - datasqlghost:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOT}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}

  ghost:
    container_name: cmsghost
    image: ghost:${GHOSTVERSION}
    restart: unless-stopped
    volumes:
      - dataghost:/var/lib/ghost/content
      - $(pwd)/conf/config.production.json:/var/lib/ghost/config.production.json:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - sqlghost

volumes:
  datasqlghost:
  datasqlghostlog:
  dataghost:
