---
version: '3.7'
services:
  traefik:
    image: traefik:chevrotin
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /local-path-to-certs:/etc/certs:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml:ro
