---
version: '3.7'
services:
  traefik:
    image: traefik:${TRAEFIKVERSION}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/traefikdynamic:/etc/traefik/dynamic:ro
      - ./logs/traefik.log:/etc/traefik/applog.log
      - ./conf/acme.json:/acme.json
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TRAEFIK_PILOT_DASHBOARD=false"

  nginx:
    image: nginx:${NGINXVERSION}
    restart: unless-stopped
    volumes:
      - nginxdata:/var/www/html
      - nginxlogs:/var/log/nginx

volumes:
  nginxdata:
  nginxlogs:
