---
version: '3.7'
services:
  traefik:
    image: traefik:${TRAEFIKVERSION}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $(pwd)/conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - $(pwd)/conf/traefikdynamic:/traefikdynamic:ro
      - $(pwd)/logs/traefik.log:/etc/traefik/applog.log
      - $(pwd)/conf/acme.json:/acme.json
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TRAEFIK_PILOT_DASHBOARD=false"

  nginxmatomo:
    image: nginx:${NGINXVERSION}
    restart: unless-stopped
    volumes:
      - datamatomo:/var/www/html
      - datanginxlogsmatomo:/var/log/nginx/
      - $(pwd)/conf/nginx-matomo:/etc/nginx/
      - /etc/localtime:/etc/localtime:ro
    links:
      - matomoapp

  sqlmatomo:
    image: mariadb:${MARIADBVERSION}
    restart: unless-stopped
    volumes:
      - $(pwd)/conf/custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf
      - datasqlmatomo:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTMATOMO}
      MYSQL_USER: ${MYSQLUSERMATOMO}
      MYSQL_PASSWORD: ${MYSQLPASSWORDMATOMO}
      MYSQL_DATABASE: ${MYSQLDBMATOMO}

  matomoapp:
    image: matomo:${MATOMOVERSION}
    restart: unless-stopped
    depends_on:
      - sqlmatomo
    environment:
      MATOMO_DATABASE_HOST: sqlmatomo
      MATOMO_DATABASE_TABLES_PREFIX: ${MYSQLTABLEPREFIXMATOMO}
      MATOMO_DATABASE_USERNAME: ${MYSQLUSERMATOMO}
      MATOMO_DATABASE_PASSWORD: ${MYSQLPASSWORDMATOMO}
      MATOMO_DATABASE_DBNAME: ${MYSQLDBMATOMO}
    volumes:
      - datamatomo:/var/www/html
      - /etc/localtime:/etc/localtime:ro

volumes:
  datamatomo:
  datanginxmatomologs:
  datasqlmatomo:
