---
version: '3.6'
services:
  traefik:
    container_name: traefik
    image: traefik:${TRAEFIKVERSION}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/traefikdynamic:/traefikdynamic:ro
      - ./logs/traefik.log:/etc/traefik/applog.log
      - ./conf/acme.json:/acme.json

  nginxmatomo:
    container_name: nginxmotomo
    image: nginx:${NGINXVERSION}
    restart: unless-stopped
    volumes:
      - datamatomo:/var/www/html
      - datanginxlogsmatomo:/var/log/nginx/
      - ./conf/nginx-matomo:/etc/nginx/
    links:
      - matomoapp

  sqlmatomo:
    container_name: sqlmatomo
    image: mariadb:${MARIADBVERSION}
    restart: unless-stopped
    volumes:
      - ./conf/custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf
      - datasqlmatomo:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTMATOMO}
      MYSQL_USER: ${MYSQLUSERMATOMO}
      MYSQL_PASSWORD: ${MYSQLPASSWORDMATOMO}
      MYSQL_DATABASE: ${MYSQLDBMATOMO}
    labels:
      traefik.enable: false

  matomoapp:
    container_name: matomoapp
    image: matomo:${MATOMOVERSION}
    restart: unless-stopped
    depends_on:
      - sqlmatomo
    environment:
      MATOMO_DATABASE_HOST: sqlmatomo
      MATOMO_DATABASE_TABLES_PREFIX: ${MYSQLTABLEPREFIXMATOMO}
      MATOMO_DATABASE_USERNAME: ${MYSQLUSERMATOMO}
      MATOMO_DATABASE_PASSWORD: ${MYSQLPASSWORDMATOMO}
      MATOMO_DATABASE_DBNAME: ${MYSQLDBMATOMO}
    volumes:
      - datamatomo:/var/www/html
    labels:
      traefik.enable: false

volumes:
  datamatomo:
  datanginxmatomologs:
  datasqlmatomo:
