---
http:
  routers:
    rt-traefik:
      entryPoints:
      - websecure
      middlewares:
      - authentification
      service: api@internal
      rule: Host (`traefik.czs.local`)
      tls:
        certResolver: letsencrypt

    rt-wordpress:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: sc-wordpress
      rule: Host (`czs.local`)
      tls:
        certResolver: letsencrypt
