---
version: '3.8'
services:
  traefik:
    container_name: traefik
    image: traefik:v2.2.5
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.toml:/etc/traefik/traefik.toml:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - dataprometheus:/etc/prometheus
    labels:
      traefik.enable: true
      traefik.http.routers.prometheus.entrypoints: web, websecure
      traefik.http.routers.prometheus.rule: Host(`prometheus.czs.local`)
      traefik.http.routers.prometheus.middlewares: authentification@file,to-https@file,security@file,compression@file
      traefik.http.routers.prometheus.tls: true

  grafana:
    container_name: grafana
    image: grafana/grafana:7.0.4
    restart: unless-stopped
    volumes:
      - datagrafana:/var/lib/grafana
      - datagrafanalogs:/var/log/grafana
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.entrypoints: web, websecure
      traefik.http.routers.grafana.rule: Host(`grafana.czs.local`)
      traefik.http.routers.grafana.middlewares: to-https@file,security@file,compression@file
      traefik.http.routers.grafana.tls: true

volumes:
  dataprometheus:
  datagrafana:
