---
# example

http:
  routers:
    rt-exampleNameRt:
      entryPoints:
      - websecure
      middlewares:
      - security
      service: sc-exampleName
      rule: Host (`fqdn.com`)
      tls:
        certResolver: cloudflare
