---
http:
  routers:
    rt-traefik:
      entryPoints:
      - websecure
      middlewares:
      - authentification
      service: api@internal
      rule: Host (`traefik.domain.name`)
      tls:
        options: default
        certResolver: letsencrypt

    rt-nginx: # example
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: sc-nginx
      rule: Host (`domain.name`)
      tls:
        options: default
        certResolver: letsencrypt
