---
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384

http:
  middlewares:
    compression:
      compress:
        excludedContentTypes:
          - text/event-stream

    security:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        addVaryHeader: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        sslRedirect: true
        sslForceHost: true
        stsPreload: true
        customFrameOptionsValue: SAMEORIGIN
        referrerPolicy: "same-origin"
        featurePolicy: "camera 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none'; vibrate 'self';"
        stsSeconds: 315360000
        hostsProxyHeaders:
          - "X-Forwarded-Host"

    authentification:
      basicAuth:
        users:
        - admin:$2y$10$byzmasKak2LLmvY86KcnGO0pX8UaaNDxQZMJW.wMmaoHRhjNXqOwG # admin/admin, use "https://bcrypt.fr" to encrypt your password

  routers:
    rt-traefik:
      entryPoints:
      - websecure
      middlewares:
      - authentification
      service: api@internal
      rule: Host (`traefik.czs.local`)
      tls:
        certResolver: letsencrypt

    rt-wordpress1:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: sc-wordpress
      rule: Host (`wp1.czs.local`)
      tls:
        certResolver: letsencrypt

    rt-wordpress2:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: sc-wordpress2
      rule: Host (`wp2.czs.local`)
      tls:
        certResolver: letsencrypt

    rt-wordpress3:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: sc-wordpress3
      rule: Host (`wp3.czs.local`)
      tls:
        certResolver: letsencrypt

  services:
    sc-wordpress1:
      loadBalancer:
        servers:
        - url: "http://nginxwp1:80"

    sc-wordpress2:
      loadBalancer:
        servers:
        - url: "http://nginxwp2:80"

    sc-wordpress3:
      loadBalancer:
        servers:
        - url: "http://nginxwp3:80"
