---
version: '3.7'
services:
  portainer:
    container_name: portainer
    image: portainer/${VERSION}
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dataportainer:/data
      - /etc/localtime:/etc/localtime:ro
    labels: # for traefik, delete this if not needed
      traefik.enable: true
      traefik.http.routers.portainer-http.entrypoints: web
      traefik.http.routers.portainer.rule: Host(`portainer.czs.local`)
volumes:
  dataportainer:
