---
version: '3.8'
services:
  traefik:
    container_name: traefik
    image: traefik:v2.2.5
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # used to have the traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
- ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/traefikdynamic:/traefikdynamic:ro      
      - ./conf/acme.json:/acme.json

  nginxnextcloud:
    container_name: nginxfornextcloud
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - datanextcloud:/var/www/html
      - datanginxnextcloudlogs:/var/log/nginx/
      - ./conf/nginx-nextcloud:/etc/nginx/conf.d
    links:
      - nextcloud
    labels:
      traefik.enable: true
      traefik.http.routers.nginxnextcloud-http.rule: Host(`nextcloud.czs.local`)
      traefik.http.routers.nginxnextcloud-http.entrypoints: web
      traefik.http.routers.nginxnextcloud-http.middlewares: https-redirect@file
      traefik.http.routers.nginxnextcloud-https.rule: "Host(`nextcloud.czs.local`)"
      traefik.http.routers.nginxnextcloud-https.entrypoints: "websecure"
      traefik.http.routers.nginxnextcloud-https.middlewares: "security@file, compression@file"
      traefik.http.routers.nginxnextcloud-https.tls: "true"
      traefik.http.routers.nginxnextcloud-https.tls.certresolver: "letsencrypt"

  nextcloud:
    container_name: nextcloudapp
    image: nextcloud:19-fpm-alpine
    restart: unless-stopped
    links:
      - dbnextcloud
    volumes:
      - datanextcloud:/var/www/html
    environment:
      MYSQL_HOST: dbnextcloud
      MYSQL_USER: nextcloudsqluser
      MYSQL_PASSWORD: nextcloudsqlpassword
      MYSQL_DATABASE: nextclouddb
      REDIS_HOST: redisnextcloud
    labels:
      traefik.enable: false

  dbnextcloud:
    container_name: sqlnextcloud
    image: mariadb:bionic
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - dbnextcloud:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_PASSWORD: nextcloudsqlpassword
      MYSQL_DATABASE: nextclouddb
      MYSQL_USER: nextcloudsqluser
    labels:
      traefik.enable: false

  redisnextcloud:
    image: redis:6
    restart: unless-stopped
    volumes:
      - dataredisnextcloud:/data
    labels:
      traefik.enable: false

volumes:
  datanextcloud:
  datadbnextcloud:
  datanginxnextcloudlogs:
  dataredisnextcloud:
