---
version: '3.7'
services:
  traefik:
    image: traefik:${TRAEFIKVERSION}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/traefikdynamic:/traefikdynamic:ro
      - ./logs/traefik.log:/etc/traefik/applog.log
      - ./conf/acme.json:/acme.json
    environment:
      TRAEFIK_PILOT_DASHBOARD: false
      TZ: "Europe/Paris"

  nginxnextcloud:
    image: nginx:${NGINXVERSION}
    restart: unless-stopped
    volumes:
      - datanextcloud:/var/www/html
      - datanginxnextcloudlogs:/var/log/nginx
      - ./conf/nginx-nextcloud:/etc/nginx
      - /etc/localtime:/etc/localtime:ro

  nextcloud:
    image: nextcloud:${NEXTCLOUDVERSION}
    restart: unless-stopped
    volumes:
      - datanextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_HOST: sqlnextcloud
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}
      REDIS_HOST: redisnextcloud
      TZ: "Europe/Paris"
    links:
      - mariadb

  mariadb:
    image: mariadb:${MARIADBVERSION}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - datadbnextcloud:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}
      TZ: "Europe/Paris"

  redis:
    image: redis:${REDISVERSION}
    restart: unless-stopped
    environment:
      TZ: "Europe/Paris"
    volumes:
      - dataredisnextcloud:/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  datanextcloud:
  datadbnextcloud:
  datanginxnextcloudlogs:
  dataredisnextcloud:
